### ISSUE TITLE
Glitch character sprites on YU-NO (English translation patch)

### ISSUE THREAD

**Issue by mozerbtww** [nunuhara/ai5-sdl2#3]
I'm having a bug where the character sprites are glitched, the background seems to be fine so far.
The last time I updated my drivers was in January of this year, I'm using 1.1.0 version and this bug persists even if i change my system region to Japanese.

![Control-V](https://github.com/user-attachments/assets/3b1e42a3-eb67-4175-8110-988c8b3dcf0c)
![Control-V (1)](https://github.com/user-attachments/assets/41af2131-75b1-4772-b29b-689fff43449a)
![Control-V (2)](https://github.com/user-attachments/assets/c0d3ddc2-ee5d-420d-a9ee-d76588578af8)

Here's my specs:
Windows 10 Pro 22H2, Build 19045.5011
Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
NVIDIA Geforce GT 1030 2GB
Gigabyte H110M-S2V-CF
8GB RAM

**Comment by nunuhara** [comment]
It looks like what's happening here is that it's using the wrong mask color when drawing the character sprites, causing the black outlines to become transparent instead of the green background of the character CG.

Unfortunately I can't reproduce this on any of my systems, so there's not much I can do to debug this myself. Can do the following:
1. Run the game with `ai5-debug.exe`
2. At the line shown in the screenshot below, hit the `F12` key
3. Type `vm-state` and hit enter at the debugger command line
4. Paste the output here (or take a screenshot)

My guess is that you will have `System.mask_color = 0000`, which will at least confirm what's happening.

![Screenshot_20241012_101943](https://github.com/user-attachments/assets/30da33d2-372d-4623-8e44-a479c3f841e9)

**Comment by mozerbtww** [comment]
yep, that's it

![image](https://github.com/user-attachments/assets/8ae81e67-83ac-42ab-a3f5-00827c60a4b0)

**Comment by nunuhara** [comment]
Okay, so the `System.mask_color` variable gets set to 8 when the game starts, and the only time it would be overwritten is when loading one of the `FLAG__` files, so I suspect the problem is in these files.

Can you replace the `FLAG__` files in your game folder with these ones and see if that fixes the issue? (Note that this will overwrite your save games, so create a backup if you want.)
[YUNO-Blank-Save.zip](https://github.com/user-attachments/files/17356083/YUNO-Blank-Save.zip)

**Comment by nunuhara** [comment]
I was able to reproduce the issue by deleting my `FLAG__` files and running the game. Restoring the files with the above .zip fixed the issue.

![Screenshot_20241013_080804](https://github.com/user-attachments/assets/b13e95ec-dec7-44c8-aa9b-8433b8b0c517)

**Comment by mozerbtww** [comment]
It worked, thank you!
